apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.appName }}-secret
  labels:
    # labels for a release management
    app: {{ .Values.appName }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
data:
  # settings for a connection to a database in PostgreSQL
  database_pass: {{ .Values.database.pass | b64enc }}
