apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  labels:
    # labels for a release management
    app: {{ .Values.appName }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  selector:
    # attache pods with this label to the service
    app: {{ .Values.appName }}
  ports:
    # the application service port
    - name: api
      port: {{ .Values.apiPort }}
      protocol: TCP
