apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    # labels for a release management
    app: {{ .Values.appName }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  # the amount of the application replicas
  replicas: {{ default 0 .Values.replicas }}
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      name: {{ .Release.Name }}
      labels:
        # labels for pods maintenance
        app: {{ .Values.appName }}
        release: {{ .Release.Name }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    spec:
      containers:
      - name: {{ .Release.Name }}
        # the application iamge
        image: {{ .Values.image }}:{{ .Values.imageTag }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        ports:
        # the application service port
          - name: http
            containerPort: {{ .Values.httpPort }}
            protocol: TCP
        # mount a config file with a virtual host configuration
        volumeMounts:
          - name: {{ .Release.Name }}-hosts
            subPath: hosts.conf
            mountPath: /etc/nginx/conf.d/hosts.conf
            readOnly: true
      # use a configmap with configuration as volume
      volumes:
        - name: {{ .Release.Name }}-hosts
          configMap:
            name: {{ .Release.Name }}-hosts
